### ISSUE TITLE
Light Curves

### ISSUE THREAD

**Issue by dmvandam** [EdanRein/pyPplusS#3]
Hi Edan,

First of all I would like to congratulate you on this code, it's great. I don't have so much an issue as perhaps a suggestion.

The light curves produced by pyPplusS are in physical space, i.e. if your occulter (whatever orientation) is a point (x,y)_o and the star is at (x,y)_s, what would the relative photometry of the star be (i.e. if 50% of the star is blocked you would get 0.5, 10% of the star is blocked you would get 0.9). 

This is great, but there is a step missing before it can be used for light curve fitting and that is the fact that, light curves are relative flux vs. time, instead of x,y position.

Would you like to introduce a transverse velocity parameter to the modelling procedure (the easiest and the way I added some modifications was to have the velocity in stellar radii/day as this gives you the units you usually want for a light curve aka days).

Another suggestion, since it is hard to know exactly where the middle of a transit is (especially if the eclipse is asymmetric) you could add a delta_time parameter that moves the eclipse left and right, though this might be of lesser interest.

Do you understand what I mean, or should I make some plots to illustrate?

Cheers and thanks for this great code!
Dirk

**Comment by EdanRein** [comment]
Hi Dirk,
Thank you very much for your suggestions and kind words.
However, I feel that they are beyond the scope of what I am trying to achieve with this package.
In my opinion, pyPplusS should fulfill this limited role, and leave it up to the end-user to decide how to convert from the orbital parameters to physical space.

Cheers,
Edan.
