### ISSUE TITLE
Package?

### ISSUE THREAD

**Issue by dmvandam** [EdanRein/pyPplusS#5]
I'm a fan and just used your code in the following paper (https://iopscience.iop.org/article/10.3847/1538-3881/abc259) and plan on using it for more of my research. I was just wondering if you could make this a "pip installable package". This is a twofold request. Foremost I believe that this is worth it, and useful for light curve analysis of ring systems and personally I would appreciate installing the package instead of copying the code contents into each of my repositories where I use pyPplusS.

**Comment by EdanRein** [comment]
Thank you for the excellent suggestion!
The code has been updated, and is now installable via pypi, at the link https://pypi.org/project/pyppluss/ or using ```pip install pyppluss```

Please let me know if there are any problems.
