### ISSUE TITLE
Rings

### ISSUE THREAD

**Issue by dmvandam** [EdanRein/pyPplusS#6]
Hello,

again great fan, and trying to get this code out there! Just a quick question, is it possible to simulate multiple rings at once (using for example LC_ringed()).

For a system as shown below I'm doing it by calculating the light curve of each of the individual rings using LC_ringed() with (planet radius = 0). Then I do:

>> light_curve = 1 + (lc_ring1 - 1) + (lc_ring2 - 1) + ....

Is there another way of doing this with pyppluss?

 
![ringsystem_19](https://user-images.githubusercontent.com/43412313/109621493-54261180-7b3b-11eb-9d7a-f08132ddf693.png)

**Comment by EdanRein** [comment]
Hello,
The way you describe is indeed the way to simulate multiple rings using pyppluss.
Your line applies the inclusion-exclusion principle in a similar fashion to what pyppluss does in its code, but it extends the logic to a case I did not account for when I wrote it.

Thank you for bringing this use case to my attention.
